-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

REVOKE ALL ON TABLE public."Images" FROM anon;
REVOKE ALL ON TABLE public."Images" FROM authenticated;
REVOKE ALL ON TABLE public."Images" FROM postgres;
REVOKE ALL ON TABLE public."Images" FROM service_role;
REVOKE ALL ON TABLE public."Images" FROM supabase_admin;
GRANT ALL ON TABLE public."Images" TO anon;

GRANT ALL ON TABLE public."Images" TO authenticated;

GRANT ALL ON TABLE public."Images" TO postgres;

GRANT ALL ON TABLE public."Images" TO service_role;

GRANT ALL ON TABLE public."Images" TO supabase_admin;

ALTER TABLE IF EXISTS public."Images"
    ADD CONSTRAINT "Images_id_key" UNIQUE (id);

REVOKE ALL ON TABLE public."Pixels" FROM anon;
REVOKE ALL ON TABLE public."Pixels" FROM authenticated;
REVOKE ALL ON TABLE public."Pixels" FROM postgres;
REVOKE ALL ON TABLE public."Pixels" FROM service_role;
REVOKE ALL ON TABLE public."Pixels" FROM supabase_admin;
GRANT ALL ON TABLE public."Pixels" TO anon;

GRANT ALL ON TABLE public."Pixels" TO authenticated;

GRANT ALL ON TABLE public."Pixels" TO postgres;

GRANT ALL ON TABLE public."Pixels" TO service_role;

GRANT ALL ON TABLE public."Pixels" TO supabase_admin;
